version: "3"
services:
  app:
    build: .
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
      bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - server_db:/var/lib/postgresql/data
volumes:
  server_db:
